INSERT INTO TB04_USUARIOS(USU_NOME, USU_EMAIL, USU_SENHA) VALUES('Welberth', 'welberth@email.com', '$2a$10$lI8PC39pxKeqa77dhdCT0.kbEVly2RQdVRIB7fiDtfgDOway5QUXu');


INSERT INTO TB04_USUARIOS(USU_NOME, USU_EMAIL, USU_SENHA) VALUES('Amanda', 'amanda@email.com', '$2a$10$lI8PC39pxKeqa77dhdCT0.kbEVly2RQdVRIB7fiDtfgDOway5QUXu');

INSERT INTO TB05_PERFIS(PER_ID, PER_NOME) VALUES(1, 'ROLE_ADMINISTRADOR');
INSERT INTO TB05_PERFIS(PER_ID, PER_NOME) VALUES(2, 'ROLE_VENDEDOR');

INSERT INTO TB04_USUARIOS_PERFIS(tb04_usuarios_usu_id, perfis_per_id) VALUES (1,1);
INSERT INTO TB04_USUARIOS_PERFIS(tb04_usuarios_usu_id, perfis_per_id) VALUES (2,2);

INSERT INTO TB01_CLIENTES(CLI_DATA_CRIACAO,CLI_NOME,CADASTRADOR_USU_ID , CLI_SALDO,CLI_SITUACAO, CLI_SOBRENOME )
VALUES('2021-12-11','Pedro',1, -45.50,'DEVEDOR','Cardoso');

INSERT INTO TB01_CLIENTES(CLI_DATA_CRIACAO,CLI_NOME,CADASTRADOR_USU_ID , CLI_SALDO,CLI_SITUACAO, CLI_SOBRENOME )
VALUES('2021-12-11','Ana',1, -55.50,'DEVEDOR','Santos');

INSERT INTO TB01_CLIENTES(CLI_DATA_CRIACAO,CLI_NOME,CADASTRADOR_USU_ID , CLI_SALDO,CLI_SITUACAO, CLI_SOBRENOME )
VALUES('2021-12-11','Tiago',1, 0,'NORMAL','Araújo');

INSERT INTO TB01_CLIENTES(CLI_DATA_CRIACAO,CLI_NOME,CADASTRADOR_USU_ID , CLI_SALDO,CLI_SITUACAO, CLI_SOBRENOME )
VALUES('2021-12-11','Marta',1, 0,'NORMAL','Araújo');

INSERT INTO TB01_CLIENTES(CLI_DATA_CRIACAO,CLI_NOME,CADASTRADOR_USU_ID , CLI_SALDO,CLI_SITUACAO, CLI_SOBRENOME )
VALUES('2021-12-11','Michael',1, 0,'NORMAL','Araújo');

INSERT INTO TB01_CLIENTES(CLI_DATA_CRIACAO,CLI_NOME,CADASTRADOR_USU_ID , CLI_SALDO,CLI_SITUACAO, CLI_SOBRENOME )
VALUES('2021-12-11','Felipe',1, 0,'NORMAL','Arruda');

INSERT INTO TB03_PRODUTOS(PRD_DATA_CADASTRO,  	PRD_DESCRICAO,  PRD_EM_ESTOQUE , PRD_PRECO_UNITARIO ,CADASTRADOR_USU_ID)
VALUES('2021-12-11', 'Macarrão', 1, 2.50, 1)